title: Jinrong Huang's Homepage
page-top-title: Jinrong Huang
top-section-bg-text: Flexible sensor and deep learning
home-subtitle: Jinrong Huang&ensp;|&ensp;黄金荣
copyright-text: '&copy; Jinrong Huang 2023-2026. All Rights Reserved.'
